<?php
/**
 * Created by PhpStorm.
 * User: jomon
 * Date: 7/3/19
 * Time: 4:42 PM
 */

namespace codexten\yii\modules\auth\controllers;


use codexten\yii\modules\auth\forms\OtpVerificationFormInterface;
use codexten\yii\web\Controller;

class OtpController extends Controller
{
    public $modelClass = OtpVerificationFormInterface::class;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionSend()
    {
        /* @var $model OtpVerificationFormInterface */
        $model = new $this->modelClass();
        $model->sendOtpSms();
    }
}