migration:
  add_access_token_column_to_user_table:
    fields: |
      access_token:'string(40):notNull'
  rename_token_table_to_user_token:
    fields: |
  alter_user_token_table:
    fields: |
model:
  rbac_auth_rule:
    ns: codexten\yii\modules\auth\models
  rbac_auth_item:
    ns: codexten\yii\modules\auth\models
  rbac_auth_item_child:
    ns: codexten\yii\modules\auth\models

